# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: variable_test.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'variable_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13variable_test.proto\x12\rvariable_test\"6\n\rFloatVariable\x12\x12\n\ndouble_val\x18\x01 \x01(\x01\x12\x11\n\tfloat_val\x18\x02 \x01(\x02\"\xd9\x01\n\x0bIntVariable\x12\x11\n\tint32_val\x18\x01 \x01(\x05\x12\x11\n\tint64_val\x18\x02 \x01(\x03\x12\x12\n\nuint32_val\x18\x03 \x01(\r\x12\x12\n\nuint64_val\x18\x04 \x01(\x04\x12\x12\n\nsint32_val\x18\x05 \x01(\x11\x12\x12\n\nsint64_val\x18\x06 \x01(\x12\x12\x13\n\x0b\x66ixed32_val\x18\x07 \x01(\x07\x12\x13\n\x0b\x66ixed64_val\x18\x08 \x01(\x06\x12\x14\n\x0csfixed32_val\x18\t \x01(\x0f\x12\x14\n\x0csfixed64_val\x18\n \x01(\x10\"H\n\rOtherVariable\x12\x10\n\x08\x62ool_val\x18\x01 \x01(\x08\x12\x12\n\nstring_val\x18\x02 \x01(\t\x12\x11\n\tbytes_val\x18\x03 \x01(\x0c\x32\xf1\x01\n\x08Transfer\x12M\n\rTransferFloat\x12\x1c.variable_test.FloatVariable\x1a\x1c.variable_test.FloatVariable\"\x00\x12G\n\x0bTransferInt\x12\x1a.variable_test.IntVariable\x1a\x1a.variable_test.IntVariable\"\x00\x12M\n\rTransferOther\x12\x1c.variable_test.OtherVariable\x1a\x1c.variable_test.OtherVariable\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'variable_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATVARIABLE']._serialized_start=38
  _globals['_FLOATVARIABLE']._serialized_end=92
  _globals['_INTVARIABLE']._serialized_start=95
  _globals['_INTVARIABLE']._serialized_end=312
  _globals['_OTHERVARIABLE']._serialized_start=314
  _globals['_OTHERVARIABLE']._serialized_end=386
  _globals['_TRANSFER']._serialized_start=389
  _globals['_TRANSFER']._serialized_end=630
# @@protoc_insertion_point(module_scope)
