# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import variable_test_pb2 as variable__test__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in variable_test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransferStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransferFloat = channel.unary_unary(
                '/variable_test.Transfer/TransferFloat',
                request_serializer=variable__test__pb2.FloatVariable.SerializeToString,
                response_deserializer=variable__test__pb2.FloatVariable.FromString,
                _registered_method=True)
        self.TransferInt = channel.unary_unary(
                '/variable_test.Transfer/TransferInt',
                request_serializer=variable__test__pb2.IntVariable.SerializeToString,
                response_deserializer=variable__test__pb2.IntVariable.FromString,
                _registered_method=True)
        self.TransferOther = channel.unary_unary(
                '/variable_test.Transfer/TransferOther',
                request_serializer=variable__test__pb2.OtherVariable.SerializeToString,
                response_deserializer=variable__test__pb2.OtherVariable.FromString,
                _registered_method=True)


class TransferServicer(object):
    """The greeting service definition.
    """

    def TransferFloat(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferInt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferOther(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransferFloat': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFloat,
                    request_deserializer=variable__test__pb2.FloatVariable.FromString,
                    response_serializer=variable__test__pb2.FloatVariable.SerializeToString,
            ),
            'TransferInt': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferInt,
                    request_deserializer=variable__test__pb2.IntVariable.FromString,
                    response_serializer=variable__test__pb2.IntVariable.SerializeToString,
            ),
            'TransferOther': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferOther,
                    request_deserializer=variable__test__pb2.OtherVariable.FromString,
                    response_serializer=variable__test__pb2.OtherVariable.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'variable_test.Transfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('variable_test.Transfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Transfer(object):
    """The greeting service definition.
    """

    @staticmethod
    def TransferFloat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/variable_test.Transfer/TransferFloat',
            variable__test__pb2.FloatVariable.SerializeToString,
            variable__test__pb2.FloatVariable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferInt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/variable_test.Transfer/TransferInt',
            variable__test__pb2.IntVariable.SerializeToString,
            variable__test__pb2.IntVariable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferOther(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/variable_test.Transfer/TransferOther',
            variable__test__pb2.OtherVariable.SerializeToString,
            variable__test__pb2.OtherVariable.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
